name: MbarrrManyItems
version: '${project.version}'
main: github.mbarrr.mbarrrmanyitems.MbarrrManyItems
api-version: 1.16
authors: [ Mbarrr ]
website: github.com/mbarrr
commands:
  Debug:
    description:
    usage: