name: MbarrrManyItems
version: '${project.version}'
main: github.mbarrr.mbarrrmanyitems.MbarrrManyItems
api-version: 1.16
authors: [ Mbarrr ]
website: github.com/mbarrr
commands:
  Debug:
    description: debug
    usage: debug
  MainMenu:
    description: Admin command for managing items
    usage: /MainMenu help